Profile review boxes fixed and popular reviews added
sloanfinger/biscuit pull request #23
Opened 2024-11-26 15:23 UTC by saraf020

That many additions/deletions are not actually anything I did besides the two sections with the popular and recent reviews. I think my IDE just reformatted it automatically upon opening it. From what I can tell, the "changes" are the same, just with different formatting.

2024-12-01 15:29 UTC, sloanfinger requested changes

2024-12-01 15:29 UTC, sloanfinger commented on src/app/(Feed)/[profile]/page.tsx
Let's also make this layout more responsive for smaller device widths!

2024-12-01 15:29 UTC, sloanfinger commented on src/app/(Feed)/[profile]/page.tsx
> +        </section>
I think we should rework these section layouts:
- Make the section a flex container (in the column direction), and move most of the padding/layout styles from the `div` up.
- Move the `h2` out of the grid, making the `Reviews` component the only child in the grid layout.

2024-12-01 15:29 UTC, sloanfinger commented on src/app/(Feed)/[profile]/page.tsx
> +              <PiRssBold className="-mb-0.5 -ml-0.5"/>
Maybe look for a more suitable icon for this section? I'd prefer we use something from the same set ([Phosphor Icons](https://react-icons.github.io/react-icons/icons/pi/)) and keep the bold weight.

2024-12-03 02:29 UTC, saraf020 commented
ESlint warning and profile review width responsiveness should be fixed

2024-12-03 02:37 UTC, sloanfinger approved these changes

2024-12-03 02:37 UTC, merged